imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    dependencies:
        before:
            - command: 'mkdir'

    tests:
        override:
            - command: 'phpunit --configuration .phpunit.xml'
              coverage:
                  file: 'build/coverage.clover'
                  format: 'php-clover'
